<div class="admin-program-detail-edit">
	<h2>Program Detail</h2>		
	<div id="admin-program-content">
		<section>
			<label>Name:</label>
			<div class="program-name <?=$this->program_detail['id']?>"><?=$this->program_detail['name']?></div>
		</section> 
		<section>
			<label>Description:</label>
			<div class="program-description <?=$this->program_detail['id']?>"><?=$this->program_detail['description']?></div>
		</section>
		<section>
			<label>Price:</label>
			<div class="program-price <?=$this->program_detail['id']?>"><?=$this->program_detail['price']?></div>
		</section>
		<section>
			<label>Measurements:</label>
			<ul id="admin-program-detail-sortable">
				<?php $count = count($this->program_measures);
				 for($i=0;$i<$count;$i++) {?>
				<li title="<?=$i?>">
					<div class="item-name">
						<span><?=$this->program_measures[$i]['name']?></span>
					</div>
					<div class="item-unit">
						<span><?=$this->program_measures[$i]['unit']?></span>
					</div>
					<div class="clear"></div>
				</li>
				<?php }?>
			</ul>
			<a class="add-item" href="#">Add</a>
		</section>
	</div>
	
	
	
	<form id="form-add-measurement" class="<?=$this->program_detail['id']?>"> 
		<p>Add new measurement</p>
		<label>Name:</label>
		<input id="mname" type="text" size="10"/>
		<label>Unit:</label>
		<input id="munit" type="text" size="10"/>
	</form>  
</div>