<div id="main-wrapper" class="clearfix">
	<div id="slideshow" class="grid_9">
		<object width="866" height="320">
			<param name="movie" value="/images/renewal_flash.swf">
			<embed src="/images/renewal_flash.swf" width="866px" height="320px">
			</embed>
		</object>
	</div>           
	<div id="content" class="grid_9" >
		<div id="welcome" class="grid_6 alpha">   
			<div class="box-padding">
				<h1>YOUR NEW LIFE STARTS TODAY</h1> 
				<p><?php print_r ($this->intro[0]['value']) ?></p>		   
			</div>
			<div class="box-padding">
				<iframe src="https://www.google.com/calendar/embed?height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=sah1buirj30lnjc95hh6lnkk9g%40group.calendar.google.com&amp;color=%23182C57&amp;ctz=America%2FNew_York" style=" border-width:0 " width="520" height="400" frameborder="0" scrolling="no"></iframe>
			</div>
		</div>
		<div id="index-program" class="grid_3 omega">
			<div class="box-padding white">						
				<ul id="index-program-list">
					<?php foreach ($this->programs as $program){ 
						if ($program->active == 1){
					?>
                        <li class="blue">
							<div>
								<span><?=$program->name;?></span>
							</div>
						</li>
						<div class="3">
							<?=$program->paypal;?>
						</div>
					<?php }}; ?>
				</ul>   
			</div>
		</div>
	</div>
</div>

