<div id="main-wrapper" class="clearfix">
	<div id="slideshow" class="grid_9">
		<object width="866" height="320">
			<param name="movie" value="/images/renewal_flash.swf">
			<embed src="/images/renewal_flash.swf" width="866px" height="320px">
			</embed>
		</object>
	</div>           
	<div id="content" class="grid_9" >
		<div id="welcome" class="grid_6 alpha">   
			<div class="box-padding">		   
				<h1>OUR NEW LIFE START TODAY</h1>
				<p>Welcome to "The Mecca" - we are the original, the place where it all began. More than 45 years ago, Joe Gold opened a modest fitness center in Venice Beach, California and began a tradition of commitment, passion and dedication that is now practiced at more than 600 locations across the globe.<p>

				<p>Our gyms are built to help people realize their goals and find their inner strength. We combine the most diverse amenities in the industry with the best personal training to deliver the ultimate fitness experience.</p>

				<p>At Gold's Gym you'll find all of the latest cardio and strength training equipment along with a dynamic group exercise program that includes classes like yoga, group cycling, mixed martial arts, muscle endurance training and pilates. Most importantly, you'll find an energetic, supportive environment full of all kinds of people who are committed to achieving their goals.
</p>
			</div>
		</div>
		<div id="classcate" class="grid_3 omega">
			<div class="box-padding white">						
				<h3>CLASS IN</h3>
				<ul>
					<li><h2>Pilates</h2></li>
					<li><h2>Yoga</h2></li>
					<li><h2>Spinning</h2></li>
					<li><h2>Strength</h2></li>
				</ul>   
			</div>
		</div>
	</div>
</div>

