<?php $this->placeholder('page')->set("testimonials") ?>
<div id="main-wrapper" class="clearfix"> 
	<div class="inner-wrapper" id="testimonials-front">
		<header class="grid_9">
			<h1>TESTIMONIALS <span>/ What Our Members Think About Us</span></h1>
		</header>
		<div class="clear"></div>
		<?php foreach ($this->testimonials as $testimonial) {?>  
		<div class="test-front-wrapper">
			<div class="grid_2">
				<div class="client-name"><?=$testimonial->name?></div>
				<div class="client-title"><?=$testimonial->from?></div>
			</div>
			<div class="grid_6 omega">
			    <?=$testimonial->content?>	
			</div>
			<div class="clear"></div>
		</div> 
		<?php }?>
		</div>  
</div>