<?php $this->placeholder('page')->set("location") ?>

<div id="main-wrapper" class="clearfix">
	<div class="inner-wrapper" id="location-front">
		<div class="grid_4">
			<header>
				<h1>LOCATION<span>/ Where are we</span></h1>
			</header>
			<img class="logo" src="/images/logo-blue.png">
			<p><?php echo $this->description;?></p>
			<p> 
				<?php echo ($this->hour != null) ? "Hours:<br>".$this->hour."<br/>":""; ?>
			</p>
			<p> 
				Address:<br>
				<?php echo $this->add1;?><br/>
				<?php echo ($this->add2 != null) ? $this->add2."<br/>":""; ?>
				<?php echo $this->city;?><br/>
				
			</p>
		</div> 
		<div class="grid_3">
			<a class='map' href="http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=415+Norwood+Avenue+Southeast,+Grand+Rapids,+MI&aq=&sll=42.684356,-84.508505&sspn=0.009228,0.013089&ie=UTF8&hq=&hnear=415+Norwood+Ave+SE,+Grand+Rapids,+Kent,+Michigan+49506&z=12&iwloc=A"><img src="http://maps.google.com/maps/api/staticmap?center=42.955200,-85.632179&zoom=13&markers=color:blue|label:A|42.955200,-85.632179&size=430x300&sensor=true"></img>
			</a>     
			
			
			
		</div>
	</div>
</div>
