<?php $this->placeholder('page')->set("location") ?>

<div id="main-wrapper" class="clearfix">
	<div class="grid_9 white">
		<div class="grid_4">
			<img style="padding-top: 10px"src="/images/logo-blue.png">
			<p> 
				Hours:<br>
				M-F 8:00 AM - 5:00 PM<br/>
			</p>
			<p> 
				Address:<br>
				100 Youell Ave SE<br/>
				Grand Rapids, MI, 49506
			</p>
		</div> 
		<div class="grid_3">
			
			<a href="http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=100+Youell+Ave+SE+Grand+Rapids,+MI,+49506&aq=&sll=42.960945,-85.63587&sspn=0.009626,0.014634&ie=UTF8&hq=&hnear=100+Youell+Ave+SE,+Grand+Rapids,+Michigan+49506&z=16&iwloc=A"><img style="padding-top:10px; padding-bottom:10px" src="http://maps.google.com/maps/api/staticmap?center=Grand+Rapids,MI&zoom=12&size=400x300&maptype=roadmap
			&markers=color:blue%7Clabel:A%7C42.960945,-85.63587&sensor=true"></img>
			</a>
		</div>
	</div>
</div>
