<!doctype html>
<html lang="en-US">
<head>
	<meta content="charset=utf-8">
	<title>Renewal Body Bootcamp</title>
	<link rel="shortcut icon" href="/images/icon-renew.ico" />
	<link rel="stylesheet" type="text/css" href="/css/reset.css" />
	<link rel="stylesheet" type="text/css" href="/css/960.css" />
	<link rel="stylesheet" type="text/css" href="/css/master.css" id="mastercss" />
	<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
	
	<script type="text/javascript" src="/js/jquery-1.6.1.js"></script>
	<script type="text/javascript" src="/js/jquery-ui-1.8.13.custom.min.js"></script>
	<script type="text/javascript" src="/js/master.js"></script>                                                        
	
 
</head>
<body>
	<div id="wrapper">                                                                         
		<div class="container_9">
			<div id="banner"> 
			<?php
				$content_model = new Application_Model_Contents();                            
	 		    $fb= $content_model
						->fetchRow($content_model->select()->where("name = 'fb_link'"))->value;
				$twt= $content_model
						->fetchRow($content_model->select()->where("name = 'twitter_link'"))->value;
			?>	
				<a id="fb-logo" href="<?php echo $fb?>">fb</a>
				<a id="twt-logo" href="<?php echo $twt?>">twt</a>
			</div>
			<div class="clear"></div> 
			<div id="navigation" class="grid_9 <?php echo $this->placeholder('page')?>">
				<ul>
					<li><a href="<?php echo $this->url(array('controller' => 'index', 'action'=>'index')); ?>">home</a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'progress', 'action'=>'index')); ?>">progress</a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'location', 'action'=>'index')); ?>">location</a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'blog', 'action'=>'index')); ?>">blog</a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'testimonials', 'action'=>'index')); ?>" class="testimonials">testimonials</a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'about', 'action'=>'index')); ?>" class="about">about</a></li>
				</ul>
			</div>
			<?php echo $this->layout()->content; ?>
			<div id="footer">
				2011 © Renewal Body Bootcamp 
				<div style="float:right; font-size:10px; ">
					<a style="text-decoration:none;" href="/admin">Admin</a>
				</div>
			</div>
			<div class="clear"></div>                  
		</div>
	</div> 
</body>