<?php echo $this->doctype() ?> 
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>Renewal Body Bootcamp</title>                           
	<link rel="stylesheet" type="text/css" href="/css/reset.css" />
	<link rel="stylesheet" type="text/css" href="/css/960.css" />
	<link rel="stylesheet" type="text/css" href="/css/master.css" />
	<script type="text/javascript" src="/js/mootools-core-1.3.2.js"></script>
	<script type="text/javascript" src="/js/master.js"></script>
	<script type="text/javascript" src="http://use.typekit.com/txq4iry.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>
<body>
	<div id="wrapper">                                                                         
		<div class="container_9">
			<div id="banner">
			</div>
			<div class="clear"></div> 
			<div id="navigation" class="grid_9 <?php echo $this->placeholder('page')?>">
				<ul>
					<li><a href="<?php echo $this->url(array('controller' => 'index', 'action'=>'index')); ?>">home</a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'progress', 'action'=>'index')); ?>">progress</a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'location', 'action'=>'index')); ?>">location</a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'blog', 'action'=>'index')); ?>">blog</a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'testimonials', 'action'=>'index')); ?>" class="testimonials">testimonials</a></li>
				</ul>
			</div>
			<?php echo $this->layout()->content; ?>
			<div id="footer">
				2011 © Renewal Body Bootcamp 
				<div style="float:right; font-size:10px; ">
					<a style="text-decoration:none;" href="/admin">Admin</a>
				</div>
			</div>
			<div class="clear"></div>                  
		</div>
	</div> 
</body>