<div id="main-wrapper" class="clearfix">
	<div class="inner-wrapper" id="progress-client-login">
		<header class="grid_9">
			<h1>PROGRESS <span>/ Your Online Fitness Portal</span></h1>
		</header>
		<div class="clear"></div>
		<div class="grid_4">
			<div style="color:red">
				<?php echo $this->message; ?>
			</div>
			<?=$this->formlogin?><br/>
			<a href="/progress/create">Create new profile</a>
		</div> 		
	</div>
</div> 
