<div id="main-wrapper" class="clearfix admin">
	<div id="enrollment" class="white">
		<div class="grid_8">
			<header>
				<h1>Administration <span>Enrollment</span></h1>
			</header>
			<?php echo $this->partial('admin/nav_partial.phtml')?>
		</div>
		<div class="clear"></div>
		<div class="grid_3">
			<table id="program-tb" width="100%">
				<tr class="title">
					<th>Programs</th>
				</tr>
			<?php foreach ($this->programs as $program){?>
				<tr class="<?=$program->id?>">
					<td class="pname"><?=$program->name?></td>
				</tr>
			<?php }?>
			</table>
			   
		</div>
		<div class="grid_2">
			<table id="user-tb" cellspacing="1px" width="100%">
				<tr class="title">
					<th>Client in program</th>
				</tr>	
			</table>
			<form>
				<input style="position:relative; top:-3px" id="add-user-to-program" readonly type="text" size="10"/>
				<img src="/images/icon-add.png"/>
			</form>	
		</div>
		<div id="measures_data" class="grid_3">
			Measurements<br>
			
		</div>       
	</div>
</div> 
