<?php 
	$this->dojo()->enable();
	echo $this->dojo(); 
?>
<div id="main-wrapper" class="clearfix">
	<div id="enrollment" class="grid_9 tundra white">
		<div class="grid_7">
			<h1>Administration</h1>
			<div>
				<a href="/admin">Dashboard</a> | 
				<a href="/admin/program">Program</a> |
				<a href="/admin/enrollment">Enrollment</a> |
				<a href="/admin/logout">Logout</a>
				<br><br>
			</div>
		</div>
		<div class="clear"></div>
		<div class="grid_3">
			<table id="program-tb" width="100%">
				<tr class="title">
					<th>Program Name</th>
				</tr>
			<?php foreach ($this->programs as $program){?>
				<tr class="<?=$program->id?>">
					<td><?=$program->name?></td>
				</tr>
			<?php }?>
			</table>
			   
		</div>
		<div class="grid_2">
			<table id="user-tb" width="100%">
				<tr class="title">
					<th>Client Name</th>
				</tr>	
				<?php if($this->users!=null) { foreach ($this->users as $user){?>
				<tr>
					<td><?=$user->fname?> <?=$user->lname?></td>
				</tr> 
				<?php }}?>   
			</table>
		    <?=$this->adduserform?>
		</div>
		<div class="grid_3">
			Measurements
			<form>
			Before
			<ul>
				<li><label for="body">Body Index:</label> 
					<input id="body" type="text" size="5"/></li>
				<li><label>Jack (per minute):</label> <input type="text" size="5"/></li>
				<li><label>Squd (per minute):</label> <input type="text" size="5"/></li>
			</ul>
			After
			<ul>
				<li><label>Body Index:</label><input type="text" size="5"/></li>
				<li><label>Jack (per minute):</label> <input type="text" size="5"/></li>
				<li><label>Squd (per minute):</label> <input type="text" size="5"/></li>
			</ul>
			
		</div>       
	</div>
</div> 
