<script type="text/javascript">
	
</script>

<div id="main-wrapper" class="clearfix">
	<div class="grid_9 white">
		<div class="grid_9">
			<h1>Programs</h1> 
			<div>
				<a href="/admin">Dashboard</a> | 
				<a href="/admin/program">Program</a> |
				<a href="/admin/enrollment">Enrollment</a> |
				<a href="/admin/logout">Logout</a>
				<br><br>
			</div>
			<h2>Program List</h2>
			<?php foreach ($this->programs as $program){?>
				<table>
					<?=$program["name"]?> 
					<a href="/admin/program/update/<?=$program["id"]?>">edit</a> | 
					<a href="/admin/program/view/<?=$program["id"]?>">view detail</a> |
					<a href="/admin/program/delete/<?=$program["id"]?>" onclick="return confirm('All users measurements of this program will be lost. Continue?')">delete</a>
				</table>
				<?php }?>
				<a href="/admin/program">Add New Program</a>
				<br>
				<br>
				
   		</div>
		<div class="grid_4">
			<h2>Add/Edit</h2>
			<?= $this->form; ?>
			<br><br>
		</div>
		<?php  if(isset($this->measures)){?>
		<div class="grid_4">
			<h2>Program Detail Measurements</h2>
			<?=$this->programDetail[0]['name']?> <br>
			<table width="100%">
				<tr>
					<th>Name</th>
					<th>Sample Value</th>
					<th>Unit</th>
				</tr> 
				<?php foreach ($this->measures as $measure){?>
					<tr> 
						<td><?=$measure[0]?></td>
						<td><?=$measure[1]?></td>
						<td><?=$measure[2]?></td>
					</tr>
				<?php }?>
			</table>
			<br><br>  
		</div>
		<?php } ?>
	</div>
	<div class="grid_3 omega">
	</div>
</div>       
