<div id="main-wrapper" class="clearfix admin">
	<div class="grid_9 white">
		<div class="grid_9">
			<h1>Classes / Series</h1> 
			<?php echo $this->partial('admin/nav_partial.phtml')?>
			<div id="admin-program-list">
				<h2>Program List</h2>
				<ul>
				<?php foreach ($this->programs as $program){?>
					<li>
						<div style="float:left; width:300px"><?=$program["name"]?></div> 
						<input class="<?=$program["id"]?> program-switch" name="checkbox.1.2" type="checkbox" id="check" <?php if ($program["active"]==1){ echo 'checked=""'; } ?> style="position: absolute; z-index: -1; visibility: hidden; ">  
						<a class="<?=$program["id"]?> program-detail ui-button-apperence" href="#">Detail</a> &nbsp; 
						<a class="<?=$program["id"]?> program-paypal ui-button-apperence" href="#">Paypal</a> &nbsp;
						<a class="ui-button-apperence" href="/admin/programdelete?id=<?=$program["id"]?>" onclick="return confirm('All users measurements of this program will be lost. Continue?')">Delete</a>  
					</li>
					<hr>				   
				<?php }?>
				</ul>
			</div>
			<br>
			<a class="program-add ui-button-apperence" href="/admin/program#add-program">Add New Program</a>
   		</div>           
		<div class="grid_4 program_left"></div>
		<div class="grid_4 program_right"></div>    
	</div>
	<div class="grid_3 omega">
	</div>
</div>       
